branches:
  only:
    - develop
language: php

php:
    - '5.6'

before_script:
    - 'composer install'

script:
    - './vendor/bin/phpunit application/tests'

after_success:
  - git clone https://github.com/arkadev/devtorgame.git
  - cd ci-buddy
  - git config --global user.email "arkadevgroup@gmail.com"
  - git config --global user.name "arkadev"
  - git checkout master
  - git merge origin/develop -m "Update to deploy"
  - git remote set-url origin https://$USER:$PASS@github.com/arkadev/devtorgame.git
  - git push origin master

notifications:

  email:
    recipients:
    - jhonvegamas@gmail.com
    - curaseco@gmail.com
    - williambgaravito@gmail.com
    on_success: never # default: change
    on_failure: always # default: always
